# Generated by Django 5.2.6 on 2025-09-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0004_proformainvoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proformainvoice",
            name="cart",
        ),
    ]
