# Generated by Django 5.2.6 on 2025-09-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0005_remove_proformainvoice_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="proformainvoice",
            name="item_total",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="tax",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="proformainvoice",
            name="order_total",
            field=models.FloatField(default=0),
        ),
    ]
