# Generated by Django 5.2.6 on 2025-09-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_item_total_alter_order_order_total_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="color",
        ),
        migrations.RemoveField(
            model_name="orderproduct",
            name="size",
        ),
    ]
